[versions]
agp = "8.4.1"
android = "2.9.5"
androidVersion = "2.6.0"
appcompatVersion = "1.3.1"
browser = "1.4.0"
converterGson = "2.9.0"
coreKtx = "1.3.0"
fragmentKtx = "1.3.6"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinStdlib = "1.6.21"
kotlinxCoroutinesAndroid = "1.3.9"
legacySupportCoreUtils = "1.0.0"
lifecycleViewmodelKtx = "2.4.0"
loggingInterceptor = "4.2.1"
lottie = "3.1.0"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
moshiKotlin = "1.11.0"
oauth = "5.9.1"
playServicesLocation = "21.1.0"
retrofit = "2.9.0"
securityCrypto = "1.1.0-alpha06"
v2All = "2.20.1"
playServicesMaps = "18.2.0"
playServices = "12.0.1"
googleGmsGoogleServices = "4.4.1"
firebaseAuth = "23.0.0"
firebaseDatabase = "21.0.0"

[libraries]
android = { module = "com.kakao.maps.open:android", version.ref = "android" }
android-v260 = { module = "com.kakao.maps.open:android", version.ref = "androidVersion" }
appcompat-v131 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
legacy-support-core-utils = { module = "androidx.legacy:legacy-support-core-utils", version.ref = "legacySupportCoreUtils" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
oauth = { module = "com.navercorp.nid:oauth", version.ref = "oauth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps-x1-0-0 = { module = "com.google.gms.play-services-maps:21.0.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
v2-all = { module = "com.kakao.sdk:v2-all", version.ref = "v2All" }
v2-cert = { module = "com.kakao.sdk:v2-cert", version.ref = "v2All" }
v2-friend = { module = "com.kakao.sdk:v2-friend", version.ref = "v2All" }
v2-navi = { module = "com.kakao.sdk:v2-navi", version.ref = "v2All" }
v2-share = { module = "com.kakao.sdk:v2-share", version.ref = "v2All" }
v2-talk = { module = "com.kakao.sdk:v2-talk", version.ref = "v2All" }
v2-user = { module = "com.kakao.sdk:v2-user", version.ref = "v2All" }
x1-0-0 = { module = "com.google.gms.play-services-maps:21.0.0" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services = { group = "com.google.android.gms", name = "play-services", version.ref = "playServices" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
googleGmsGoogleServices = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

